#Makefile

ARCH_TYPE = WIN64
DEBUG_FLAGS = -g -W -Wall
CC_FLAGS = -m64 -mno-stack-arg-probe
CPP_FLAGS = -m64 -mno-stack-arg-probe
LD_CC_FLAGS = $(CC_FLAGS) -Wl,-static -s
LD_CPP_FLAGS = $(CPP_FLAGS) -Wl,-static -s
CC_OPT_0 = -O0
CC_OPT_2 = -O3
CPP_OPT_0 = -O0
CPP_OPT_2 = -O3
CC = x86_64-w64-mingw32-gcc
CPP = x86_64-w64-mingw32-g++
LD_CC = $(CC)
LD_CPP = $(CPP)
LIB_PREFIX = 
LIB_SUFFIX = .lib

include Makefile.common

# DO NOT DELETE
