#Makefile

ARCH_TYPE = MacOSX-x86-64
DEBUG_FLAGS = -g -Wextra -Wall -Wconversion -Wno-sign-conversion
CC_FLAGS = -m64
CPP_FLAGS = -m64
LD_CC_FLAGS = $(CC_FLAGS)
LD_CPP_FLAGS = $(CPP_FLAGS)
CC_OPT_0 = -O0
CC_OPT_2 = -O3
CPP_OPT_0 = -O0
CPP_OPT_2 = -O3
CC = clang
CPP = clang++
LD_CC = $(CC)
LD_CPP = $(CPP)
LIB_PREFIX = lib
LIB_SUFFIX = .a

include Makefile.common

# DO NOT DELETE
